# Generated by Django 5.2.9 on 2025-12-21 01:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='platos',
        ),
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
        migrations.AddField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADO', 'Finalizado'), ('CANCELADO', 'Cancelado (No Finalizado)')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='pedido',
            name='motivo_cancelacion',
            field=models.CharField(blank=True, choices=[('SIN_INSUMOS', 'Falta de Insumos'), ('FUERZA_MAYOR', 'Motivos de Fuerza Mayor'), ('CLIENTE_NO_APARECIO', 'Cliente no se presentó'), ('OTRO', 'Otros')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
