# Generated by Django 5.2.9 on 2025-12-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('total', models.IntegerField(default=0)),
                ('cliente', models.CharField(default='Cliente App', max_length=100)),
                ('platos', models.ManyToManyField(to='restaurante.plato')),
            ],
        ),
    ]
