# Generated by Django 5.2.9 on 2025-12-21 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0002_remove_pedido_platos_remove_pedido_total_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='platos',
            field=models.ManyToManyField(to='restaurante.plato'),
        ),
        migrations.AddField(
            model_name='pedido',
            name='total',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='plato',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
