# Generated by Django 5.2.9 on 2025-12-22 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurante', '0004_pedido_repartidor_alter_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente (Esperando confirmación)'), ('COCINANDO', 'En Preparación (Cocinando)'), ('LISTO', 'Listo para Recogida (Esperando Repartidor)'), ('EN_CAMINO', 'En Camino'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20),
        ),
    ]
